### ISSUE TITLE
Calls to Gurobi fails after a garbage collection has taken place

### ISSUE THREAD

**Issue by bunelr** [bamos/gurobi.torch#4]
**How to reproduce the bug:**
Trigger a garbage collection after the bindings have been loaded and try to call a function.

Example:
At the beginning of `test.lua`, add call to the garbage collection after requiring gurobi:

```
local gurobi = require 'gurobi'
collectgarbage()
collectgarbage()
```

Results:

```
$ th test.lua 
Running 5 tests
1/5 SmallLP ............................................................. [WAIT]/home/rudy/workspace/torch/install/bin/luajit: symbol lookup error: /home/rudy/workspace/torch/install/lib/lua/5.1/libgurobi.so: undefined symbol: GRBloadenv
```

Cause: 
The symbols loaded [here](https://github.com/bamos/gurobi.torch/blob/master/init.lua#L13) are garbage collected and therefore can not be found.

**Comment by bamos** [comment]
Corrected in your PR #5.
